<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nader Hotait">

<title>TikTok and (Anti)Radicalism: A Study on German Muslim Content Creators</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">TikTok and (Anti)Radicalism: A Study on German Muslim Content Creators</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nader Hotait </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="topic-and-indicator-frequency" class="level2">
<h2 class="anchored" data-anchor-id="topic-and-indicator-frequency">Topic and Indicator Frequency</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Topics</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Take-Aways</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 78%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Topic</th>
<th style="text-align: right;">Count</th>
<th style="text-align: left;">Content</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">advoc</td>
<td style="text-align: right;">1144</td>
<td style="text-align: left;">Religious Advocacy, Reminders, Teaching</td>
</tr>
<tr class="even">
<td style="text-align: left;">lifestyle</td>
<td style="text-align: right;">593</td>
<td style="text-align: left;">Clothing, Food, Travel, Music, Dance</td>
</tr>
<tr class="odd">
<td style="text-align: left;">kinship</td>
<td style="text-align: right;">385</td>
<td style="text-align: left;">Partnership, Parent-Children relations</td>
</tr>
<tr class="even">
<td style="text-align: left;">moral</td>
<td style="text-align: right;">295</td>
<td style="text-align: left;">Moral Constitution/Morality of Society/People</td>
</tr>
<tr class="odd">
<td style="text-align: left;">lawful</td>
<td style="text-align: right;">272</td>
<td style="text-align: left;">What is allowed/not allowed in Islam (haram/halal)</td>
</tr>
<tr class="even">
<td style="text-align: left;">motivation</td>
<td style="text-align: right;">206</td>
<td style="text-align: left;">Empowering People to strive for better</td>
</tr>
<tr class="odd">
<td style="text-align: left;">history</td>
<td style="text-align: right;">165</td>
<td style="text-align: left;">Stories from History, History as a topic</td>
</tr>
<tr class="even">
<td style="text-align: left;">ramadan</td>
<td style="text-align: right;">147</td>
<td style="text-align: left;">Ramadan and Fasting</td>
</tr>
<tr class="odd">
<td style="text-align: left;">afterlife</td>
<td style="text-align: right;">144</td>
<td style="text-align: left;">Death, Heaven, Hell</td>
</tr>
<tr class="even">
<td style="text-align: left;">gender</td>
<td style="text-align: right;">124</td>
<td style="text-align: left;">Gender Relations</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scarf</td>
<td style="text-align: right;">110</td>
<td style="text-align: left;">Hijab, Headscarf, Veiling</td>
</tr>
<tr class="even">
<td style="text-align: left;">conversion</td>
<td style="text-align: right;">73</td>
<td style="text-align: left;">Convert Stories, Conversion to Islam</td>
</tr>
<tr class="odd">
<td style="text-align: left;">western_hypo</td>
<td style="text-align: right;">68</td>
<td style="text-align: left;">Hypocrisy of the West/Western countries<br>towards Muslims compared to others</td>
</tr>
<tr class="even">
<td style="text-align: left;">education</td>
<td style="text-align: right;">65</td>
<td style="text-align: left;">Education (Personal, School, etc.)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">shirk</td>
<td style="text-align: right;">60</td>
<td style="text-align: left;">Monotheism and Polytheism</td>
</tr>
<tr class="even">
<td style="text-align: left;">comedy</td>
<td style="text-align: right;">53</td>
<td style="text-align: left;">Funny and Humoristic Videos</td>
</tr>
<tr class="odd">
<td style="text-align: left;">media</td>
<td style="text-align: right;">51</td>
<td style="text-align: left;">Media Entities, Reports, Outlets as a Topic</td>
</tr>
<tr class="even">
<td style="text-align: left;">crime</td>
<td style="text-align: right;">41</td>
<td style="text-align: left;">Crime, Criminality, Delinquency</td>
</tr>
<tr class="odd">
<td style="text-align: left;">discrimination</td>
<td style="text-align: right;">41</td>
<td style="text-align: left;">Discrimination, Racism, Islamophobia</td>
</tr>
<tr class="even">
<td style="text-align: left;">middle_east</td>
<td style="text-align: right;">38</td>
<td style="text-align: left;">Israel-Palestine Conflict</td>
</tr>
<tr class="odd">
<td style="text-align: left;">business</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Finance, How to make Money</td>
</tr>
<tr class="even">
<td style="text-align: left;">rap</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">Rap Music and Personalities</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ijma</td>
<td style="text-align: right;">13</td>
<td style="text-align: left;">Islamic Jurisprudence given from consensus</td>
</tr>
<tr class="even">
<td style="text-align: left;">rolemodels</td>
<td style="text-align: right;">13</td>
<td style="text-align: left;">Islamic and Popcultural Rolemodels</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>Religious Advocacy (kurz advoc) ist mit 1144 kodierten Videos das am häufigste Topic in der Studie. Primär sind zweierlei Gründe zu nennen: 1) Unser Fokus beim Sampeln auf Accounts mit dezidiert religiösen (islamischen) Inhalten, 2) Das Nutzen von Advoc als „allgemeine Kategorie“, die auch dann genutzt worden ist, wenn keine anderen Codes zum Thema Religion gepasst haben. Nichtsdestotrotz, es zeigt damit auch einfach, dass (selbstverständlich) die Vermittlung religiöser Inhalte bei eben solchen Accounts am obersten rangieren.</p>
<p>Grundsätzlich ist der Funktion solcher religiösen Accounts irgendwo auch eine, der „muslimischen Diaspora“ also die Rolle deutscher oder gar europäischer Muslime in Kontexten in denen Sie die Minderheit darstellen. Das Bedürfnis nach Orientierung und Antworten auf Lebensfragen, die sich überhaupt erst stellen im deutschen Kontext, erklärt überhaupt diese starke Präsenz von Accounts mit ebensolchen Inhalten. Diese Vermutung wird unterstrichen vom Fakt, dass einige Videos Themen in diesem Nexus aufgreifen oder zumindest Ausdruck gewisser Hybridität sind. Beispielsweise das Thema „lifesstyle“ (593). Wiederum zwei Dinge kommen hier zum Ausdruck: 1) Die Marktlogiken der TikTok-Attention-Economy die natürlich unter der ultima ratio den Algorhitmus zu befrieden, wirken auch auf religiös-muslimische Accounts. Ähnlich wie ihre Peers referieren sie gleich nach ihrem „Hauptthema“ auf lifestyle-matter, da dies der TikTok Kultur am ehesten entspricht, vielleicht auch die demografisch-geleiteten Interessen widerspiegeln. Ähnlich verhält es sich zu Theman wie „lawful“ (272), welches auch des Öfteren auftaucht und die Suche nach Antworten widerspiegelt, die oftmals in mehrheitlich Muslimischen Kontexten meist als selbstverständlich zu erachten sind. Was kann man machen/was nicht im Westen. Ähnlich mit Geschlechterverhältnissen („gender“, 124). Die Navigation islamischer Glaubenslehren und ihre Rolle, Umdeutungen vis-a-vis westlicher Moral- und Geschlechtervorstellungen. Die Theman zeigen quasi das diese Accounts eine Funktion erfüllen, die der des Sinnstiftens aber auch der moralisch-praxiologischen Orientierung im Zusammenspiel verschiedener Identitäten und der des Orientierungsbedürfnis nahe kommt.</p>
<p>Das Spannungsfeld „Muslime und der Westen“ wird explizit durch relativ häufige Nennungen von Theman Rund um das Kopftuch („scarf“, 110), Konvertierungen zum Islam („conversion“, 73), Herausarbeiten von westlicher Doppelmoral im Bezug zu muslimen („western_hypo“, 96), Diskriminierungserfahrungen („discrimination“, 41) und dem Nahohst-Konflikt („middle_east“, 38). Alle außer conversion tauche gehäuft mit dem Indikator „victim“ auf, was darauf hindeutet, dass es um die erlebte und wahrgenommene Viktimisierung als Muslim oder von Muslimen als soziale Entität ein zentrales Thema ist für Muslime und maßgeblich davon geprägt sind, dass die durch das Internet solidaritätsräume suchen oder ihre moralisch-politisches Präskription hierdurch legitimieren. Auch zeugt es von der Politisierung ihrer intersektionellen Identitäten, entlang Migration, Religion, Geschlecht usw.</p>
<p>Andere Themen sind zeugen unmittelbar von muslimischen in Deutschland, als ein kulturelles Phänomen, wie Comedy und Rap.</p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Indicators</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Take-Aways</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 7%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 81%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Indicator</th>
<th style="text-align: right;">Total</th>
<th style="text-align: left;">Codes</th>
<th style="text-align: right;">Count</th>
<th style="text-align: left;">Content</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">victim</td>
<td style="text-align: right;">150</td>
<td style="text-align: left;">*</td>
<td style="text-align: right;">150</td>
<td style="text-align: left;">Victimization of the in-group, Muslims/Muslim nations. Not: Discrimination of other groups (see topic: discrimination)</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">anti_*</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Recognition of Muslim agency, portrayal as aggressor</td>
</tr>
<tr class="odd">
<td style="text-align: left;">vioreg</td>
<td style="text-align: right;">150</td>
<td style="text-align: left;">*</td>
<td style="text-align: right;">22</td>
<td style="text-align: left;">Authoritarian theology of a vengeful, stern God/religion and no error tolerance</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">anti_*</td>
<td style="text-align: right;">128</td>
<td style="text-align: left;">Belief in a merciful, understanding God with tolerance for human imperfection</td>
</tr>
<tr class="odd">
<td style="text-align: left;">monism</td>
<td style="text-align: right;">47</td>
<td style="text-align: left;">*</td>
<td style="text-align: right;">24</td>
<td style="text-align: left;">Belief in a single, exclusively true interpretation and practice of Islam, while rejecting differing opinions and ambiguities</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">anti_*</td>
<td style="text-align: right;">23</td>
<td style="text-align: left;">Embracing religious pluralism, tolerance of ambiguity, gray scales, and acceptance of diverse interpretations and practices within Islam</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activism</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">*</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">Legal political activism (Protest, Boycott, Art)</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">anti_*</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Against activism:</td>
</tr>
<tr class="odd">
<td style="text-align: left;">emancipation</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">*</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">Emancipation of people/groups (typically women and children), rights to education, etc.</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">anti_*</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Dependence of people/groups, with limited or no access to rights and education</td>
</tr>
<tr class="odd">
<td style="text-align: left;">interfaith</td>
<td style="text-align: right;">17</td>
<td style="text-align: left;">*</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">Embracing interfaith cohesion/exchange/collaboration/respect</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">anti_*</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Rejection of interfaith cohesion/exchange/collaboration/respect</td>
</tr>
<tr class="odd">
<td style="text-align: left;">delegitim</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">*</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">Belief in the illegitimacy/obsolescence of (German) democracy, political institutions, and the fundamental socio-political system</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">anti_*</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Belief in their legitimacy</td>
</tr>
<tr class="odd">
<td style="text-align: left;">closure</td>
<td style="text-align: right;">11</td>
<td style="text-align: left;">*</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Discrimination and exclusion of people from certain spaces and social life</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">anti_*</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Against closure, granting access to spaces, favoring friendships/ties</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sectarianism</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">*</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">Denigration of other religious currents and exclusion of denominations from Islam that self-identify as such/Takfirism</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">anti_*</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Promotion of religious inclusivity and acceptance of diverse Islamic denominations</td>
</tr>
<tr class="odd">
<td style="text-align: left;">revisionism</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">*</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Reestablishment of the Islamic Caliphate or other past dynasties. Unification of Muslim peoples under one rule/Caliphate</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">anti_*</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Opposition to restoring past Islamic dynasties, advocating for separate, independent governance among Muslim communities</td>
</tr>
<tr class="odd">
<td style="text-align: left;">dehuman</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">*</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Denying humanity of others, harsh insults</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">anti_*</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Against dehumanization, defending people against it</td>
</tr>
<tr class="odd">
<td style="text-align: left;">dichotom</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">*</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Dividing the world, society, and groups into friend and foe</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">anti_*</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Seeing the world, society, and groups beyond friend and foe distinctions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">violence</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">*</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Use of physical violence to achieve political/religious goals. Jihadist rhetoric</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">anti_*</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Pursuit of political/religious goals through non-violent means, emphasizing peaceful discourse</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<p>Hier spiegeln sich (ähnlich zu Ramis Argumenten) dreirlei Patterns auf: Rolle von religiösen Auslegung,Pluralismus/Monismuis, Gewalt Affinität als politisches Mittel und Anti-Demokratischen/Anti-Establishment Narrativen. Dominanteste (Unter-)Kategorie ist „victim“ (150). Diese Kategorie ist eine neutrale, insofern, es selbst kein (meist) kein Radikalisierungsindikator ist aber ein Einfallstor oder potentes Narrativ. Es unterschreicht die Relevanz muslim/islam bezogener Anfeindungen, Misstände, Diskriminerungen, die in- oder auslands erlebt oder mitgefühlt werden (gegen über der „ingroup“). Interessanterweise steht direkt dahinter, als quasi theologische Kategorie „vioreg“ als eine Auslegungsform des Islams als Religion und nicht als soziale Einheit. Die allermeisten Videos sind hierbei genau andersherum gepolt gwesen („anti_vioreg“, 128), was zeigt, das bei den aller meisten Videos, eine Auslegung vom Islam stattfindet, die meist rücksichtsvoll und bahmherzig ist. Bei den meisten sicher Ernst gemeint, bei einigen übernimmt es sicherlich die Funktion der „humaniizing“ des Akteurs und seiner Message. In Richtung politisch orietneriten Extremismus (gewalt, deligimation etc.) scheitn es so, dass legaler POltiischer Aktivismus weit aus öfter vertreten ist als Gewalt oriernite, jedoch finden sich gehäuft Deligitimationen des hiesigen rechtsstaates statt (meist in Verbindung mit Victim usw.)</p>
</div>
</div>
</div>
</section>
<section id="co-occurances-victim" class="level2">
<h2 class="anchored" data-anchor-id="co-occurances-victim">Co-Occurances: Victim</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">Graph</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">Table</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-3" role="tab" aria-controls="tabset-3-3" aria-selected="false" href="">Take-Aways</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/victim%20bipartit-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div id="tbl-victim" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-victim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Co-Occurances of Radicalism Indicators and Topics with “Victim”
</figcaption>
<div aria-describedby="tbl-victim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Radicalism</th>
<th>n</th>
<th>Topic</th>
<th>n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>activism</td>
<td>9</td>
<td>western_hypo</td>
<td>52</td>
</tr>
<tr class="even">
<td>delegitim</td>
<td>6</td>
<td>media</td>
<td>30</td>
</tr>
<tr class="odd">
<td>interfaith</td>
<td>5</td>
<td>scarf</td>
<td>30</td>
</tr>
<tr class="even">
<td>dichotom</td>
<td>2</td>
<td>middle_east</td>
<td>23</td>
</tr>
<tr class="odd">
<td>emancipation</td>
<td>2</td>
<td>crime</td>
<td>20</td>
</tr>
<tr class="even">
<td>revisionism</td>
<td>2</td>
<td>discrimination</td>
<td>20</td>
</tr>
<tr class="odd">
<td>anti_dehuman</td>
<td>1</td>
<td>advoc</td>
<td>15</td>
</tr>
<tr class="even">
<td>dehuman</td>
<td>1</td>
<td>history</td>
<td>14</td>
</tr>
<tr class="odd">
<td>monism</td>
<td>1</td>
<td>gender</td>
<td>12</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>moral</td>
<td>8</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>motivation</td>
<td>8</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>kinship</td>
<td>5</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>conversion</td>
<td>4</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>education</td>
<td>4</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>ramadan</td>
<td>3</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>lifestyle</td>
<td>2</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>shirk</td>
<td>2</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>lawful</td>
<td>1</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>rap</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<div id="tabset-3-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-3-tab">
<ul>
<li>Aufjedenfall Paper nochmal lesen und dort die Argumente und Zusammenhänge anschauen und Beispiele überlegen</li>
<li>Folgende Zusammenhänge Interessant (Quali Beispiele):
<ul>
<li>Victim und die Handlungslösungen diesbezüglich im Kontrast zwischen activism und radikalen Hanldungen/Lösungen (Tabelle)</li>
<li>Victim und die Projektion auf betimmte Themen, auf welcher Grundlage wird Victimhood verspürt und ihr Zusammenhang zum Leben als (muslimische) Minderheit in Deutschland (Tabelle)</li>
</ul></li>
<li>Folgende Zusammenhänge zwischen Themen und Indikatoren innerhalb von Victim interressant für Beispiele (Graph):
<ul>
<li>western_hypo + (deligitim, interfaith) = westen hypocracy als gurndlage für deligitmierung aber auch als apell für mer interfaith dialog</li>
<li>scarf + (emancipation, activism) = hijab als gegestand emanzipatorischer diskurse und fundament für (legalen) politischen aktivismus</li>
<li>interfaith - discrimination = discrimination als grundlage der nivilierung zwischen muslimen und nicht muslimien</li>
<li>deligitim + advoc = religiös begründetet deligiimation des staates z.b.</li>
</ul></li>
</ul>
</div>
</div>
</div>
</section>
<section id="co-occurances-advoc" class="level2">
<h2 class="anchored" data-anchor-id="co-occurances-advoc">Co-Occurances: Advoc</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true" href="">Graph</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false" href="">Table</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-3" role="tab" aria-controls="tabset-4-3" aria-selected="false" href="">Take-Aways</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/bipartite-advoc-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div id="tbl-advoc" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-advoc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Co-Occurances of Radicalism Indicators and Topics with “Advoc”
</figcaption>
<div aria-describedby="tbl-advoc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Radicalism</th>
<th>n</th>
<th>Topic</th>
<th>n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>anti_vioreg</td>
<td>64</td>
<td>lifestyle</td>
<td>103</td>
</tr>
<tr class="even">
<td>victim</td>
<td>15</td>
<td>motivation</td>
<td>91</td>
</tr>
<tr class="odd">
<td>anti_monism</td>
<td>9</td>
<td>kinship</td>
<td>63</td>
</tr>
<tr class="even">
<td>monism</td>
<td>9</td>
<td>moral</td>
<td>43</td>
</tr>
<tr class="odd">
<td>delegitim</td>
<td>5</td>
<td>afterlife</td>
<td>41</td>
</tr>
<tr class="even">
<td>interfaith</td>
<td>5</td>
<td>gender</td>
<td>30</td>
</tr>
<tr class="odd">
<td>vioreg</td>
<td>5</td>
<td>education</td>
<td>28</td>
</tr>
<tr class="even">
<td>sectarianism</td>
<td>4</td>
<td>history</td>
<td>24</td>
</tr>
<tr class="odd">
<td>activism</td>
<td>3</td>
<td>lawful</td>
<td>24</td>
</tr>
<tr class="even">
<td>emancipation</td>
<td>3</td>
<td>shirk</td>
<td>19</td>
</tr>
<tr class="odd">
<td>revisionism</td>
<td>3</td>
<td>ramadan</td>
<td>17</td>
</tr>
<tr class="even">
<td>anti_closure</td>
<td>2</td>
<td>media</td>
<td>11</td>
</tr>
<tr class="odd">
<td>dehuman</td>
<td>2</td>
<td>conversion</td>
<td>10</td>
</tr>
<tr class="even">
<td>anti_emancipation</td>
<td>2</td>
<td>business</td>
<td>9</td>
</tr>
<tr class="odd">
<td>closure</td>
<td>1</td>
<td>scarf</td>
<td>7</td>
</tr>
<tr class="even">
<td>anti_dichotom</td>
<td>1</td>
<td>comedy</td>
<td>6</td>
</tr>
<tr class="odd">
<td>dichotom</td>
<td>1</td>
<td>rap</td>
<td>4</td>
</tr>
<tr class="even">
<td>anti_interfaith</td>
<td>1</td>
<td>rolemodels</td>
<td>4</td>
</tr>
<tr class="odd">
<td>anti_sectarianism</td>
<td>1</td>
<td>western_hypo</td>
<td>4</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>crime</td>
<td>3</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>discrimination</td>
<td>2</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>ijma</td>
<td>2</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>middle_east</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<div id="tabset-4-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-3-tab">
<ul>
<li>Aufjedenfall Paper nochmal lesen und dort die Argumente und Zusammenhänge anschauen und Beispiele überlegen</li>
<li>Folgende Zusammenhänge Interessant (Tabelle; Quali Beispiele):
<ul>
<li>Der hohe Anteil von Lifestyle, privatleben related topics mit Advocacy (lifestyle, motivation, kinship, gender) noch VOR sehr theologischen Themen wie shirk, afterlife ==&gt; die soziale Funktion von Dawah Accoutns im Westen/Deutschland</li>
<li>natürlich viel höre co-inzidenz von rad. indikatoren die auf theologischen Aspekten beruhen: anti_vioreg, aber auch victim zwei stärkstes thema == also wir haben sone dimension einmal politics auf der einen seite und dann auf anderen seite religious advocacy als theologisches ding aber brücken indikator ist viktim als prägender faktore welches das leben von muslimen in deutschland bezeichnet, so sehr dass die soziale wie religiöse diskure des islams darauf münzt</li>
</ul></li>
<li>Folgende Zusammenhänge zwischen Themen und Indikatoren innerhalb von Advoc interressant für Beispiele (Graph):
<ul>
<li>Monism und anti_monism natürlich stärkeren bezug zu lawful (etwas haram oder hala nicht- da hast du dimension von leuten die eher ambiguitäten erlauben und manche simplifizieren)</li>
<li>Victim + Geschlecht (unter advoc): yani Frauen als mehrfach diskriminiert, hybervisible als Muslimisch (scarf) und daher diese überlappung von Religiöser Ansprache, Victim und Gender zu gleich (auch zu gleich diese viktimisierung von Frauen vielleicht vom Westen aus)</li>
<li>anti_vioreg + motivation: dieses nicht verzagen gott ist bahmherzig ist hier ganz wichtig als narrativ. weil es zu einem seelsorge, dawah, motivation kombiniert und zu gleich die Realitäten anspricht von vielleicht Jugendlichen die nicht wissen ob Sie als Muslime richtig praktizieren oder vielen versuchungen ausgesetzt werden, und ihre identität finden. aber ich finde das ganz interessant als dominantes narrativ: hoffnung usw. zieht sich bisschen durch alle lifestyle topics</li>
</ul></li>
</ul>
</div>
</div>
</div>
</section>
<section id="gender-and-activity" class="level2">
<h2 class="anchored" data-anchor-id="gender-and-activity">Gender and Activity</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true" href="">Table</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false" href="">Take-Aways</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Topic</strong></th>
<th><strong>Female</strong></th>
<th><strong>Male</strong></th>
<th><strong>Avg.Likes</strong></th>
<th><strong>Avg.Views</strong></th>
<th><strong>Avg.Duration</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>comedy</td>
<td>5%</td>
<td>0.4%</td>
<td>17150</td>
<td>552373</td>
<td>20</td>
</tr>
<tr class="even">
<td>lifestyle</td>
<td>39.6%</td>
<td>8.8%</td>
<td>26303</td>
<td>385333</td>
<td>37</td>
</tr>
<tr class="odd">
<td>kinship</td>
<td>12.6%</td>
<td>8.3%</td>
<td>17466</td>
<td>216151</td>
<td>62</td>
</tr>
<tr class="even">
<td>conversion</td>
<td>2.3%</td>
<td>1.7%</td>
<td>18351</td>
<td>175363</td>
<td>79</td>
</tr>
<tr class="odd">
<td>lawful</td>
<td>1.1%</td>
<td>7.9%</td>
<td>11072</td>
<td>146012</td>
<td>69</td>
</tr>
<tr class="even">
<td>western_hypo</td>
<td>0.4%</td>
<td>2%</td>
<td>9673</td>
<td>127561</td>
<td>86</td>
</tr>
<tr class="odd">
<td>education</td>
<td>2.2%</td>
<td>1.6%</td>
<td>14082</td>
<td>111535</td>
<td>56</td>
</tr>
<tr class="even">
<td>crime</td>
<td>0.4%</td>
<td>1.2%</td>
<td>8036</td>
<td>100116</td>
<td>74</td>
</tr>
<tr class="odd">
<td>shirk</td>
<td>0.9%</td>
<td>1.6%</td>
<td>9138</td>
<td>99500</td>
<td>130</td>
</tr>
<tr class="even">
<td>advoc</td>
<td>8.1%</td>
<td>30.1%</td>
<td>12175</td>
<td>94389</td>
<td>52</td>
</tr>
<tr class="odd">
<td>gender</td>
<td>2%</td>
<td>3.4%</td>
<td>6786</td>
<td>91989</td>
<td>70</td>
</tr>
<tr class="even">
<td>afterlife</td>
<td>0.7%</td>
<td>4.1%</td>
<td>9734</td>
<td>83113</td>
<td>69</td>
</tr>
<tr class="odd">
<td>rolemodels</td>
<td>0%</td>
<td>0.4%</td>
<td>8279</td>
<td>82867</td>
<td>78</td>
</tr>
<tr class="even">
<td>media</td>
<td>0.5%</td>
<td>1.4%</td>
<td>7568</td>
<td>80675</td>
<td>72</td>
</tr>
<tr class="odd">
<td>motivation</td>
<td>3.4%</td>
<td>5.3%</td>
<td>10157</td>
<td>75648</td>
<td>55</td>
</tr>
<tr class="even">
<td>moral</td>
<td>5%</td>
<td>7.9%</td>
<td>7758</td>
<td>73022</td>
<td>88</td>
</tr>
<tr class="odd">
<td>ramadan</td>
<td>2%</td>
<td>4%</td>
<td>7202</td>
<td>69800</td>
<td>63</td>
</tr>
<tr class="even">
<td>scarf</td>
<td>9%</td>
<td>1.8%</td>
<td>5587</td>
<td>62271</td>
<td>61</td>
</tr>
<tr class="odd">
<td>middle_east</td>
<td>0%</td>
<td>1.1%</td>
<td>6003</td>
<td>56628</td>
<td>108</td>
</tr>
<tr class="even">
<td>rap</td>
<td>0.5%</td>
<td>0.5%</td>
<td>3253</td>
<td>39615</td>
<td>46</td>
</tr>
<tr class="odd">
<td>discrimination</td>
<td>0.9%</td>
<td>1.1%</td>
<td>2727</td>
<td>38586</td>
<td>155</td>
</tr>
<tr class="even">
<td>history</td>
<td>0.9%</td>
<td>4.8%</td>
<td>3298</td>
<td>33854</td>
<td>152</td>
</tr>
<tr class="odd">
<td>ijma</td>
<td>0%</td>
<td>0.4%</td>
<td>876</td>
<td>27654</td>
<td>92</td>
</tr>
<tr class="even">
<td>business</td>
<td>2.3%</td>
<td>0.4%</td>
<td>1979</td>
<td>21970</td>
<td>88</td>
</tr>
</tbody>
</table>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<p>See Paper</p>
</div>
</div>
</div>
</section>
<section id="status-and-topical-diversity" class="level2">
<h2 class="anchored" data-anchor-id="status-and-topical-diversity">Status and Topical Diversity</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/status-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="retrieved-accounts-pseudonoyms-and-activity" class="level2">
<h2 class="anchored" data-anchor-id="retrieved-accounts-pseudonoyms-and-activity">Retrieved Accounts, Pseudonoyms, and Activity</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true" href="">Table</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false" href="">Activity Graph</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-3" role="tab" aria-controls="tabset-6-3" aria-selected="false" href="">By Account</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Account</strong></th>
<th><strong>Pseudonym</strong></th>
<th><strong>Status</strong>*</th>
<th><strong>Available</strong></th>
<th><strong>Gender</strong></th>
<th><strong>Videos</strong></th>
<th><strong>Start</strong></th>
<th><strong>End</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>abumikail1</td>
<td>PT1</td>
<td>Identified</td>
<td>TRUE</td>
<td>male</td>
<td>123</td>
<td>01.01.2022</td>
<td>28.12.2022</td>
</tr>
<tr class="even">
<td>amal_tvv</td>
<td>PT2</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>female</td>
<td>72</td>
<td>02.01.2022</td>
<td>23.12.2022</td>
</tr>
<tr class="odd">
<td>bjoernslife</td>
<td>PT3</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>male</td>
<td>70</td>
<td>02.01.2022</td>
<td>29.12.2022</td>
</tr>
<tr class="even">
<td>circassian.eagle</td>
<td>PT4</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>male</td>
<td>83</td>
<td>02.01.2022</td>
<td>27.12.2022</td>
</tr>
<tr class="odd">
<td>dawahgang</td>
<td>PT5</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>male</td>
<td>18</td>
<td>01.01.2022</td>
<td>07.06.2022</td>
</tr>
<tr class="even">
<td>deen_akademie</td>
<td>PT6</td>
<td>Identified</td>
<td>TRUE</td>
<td>male</td>
<td>73</td>
<td>17.08.2022</td>
<td>30.12.2022</td>
</tr>
<tr class="odd">
<td>deen_ul_islam1</td>
<td>PT7</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>female</td>
<td>21</td>
<td>22.12.2022</td>
<td>31.12.2022</td>
</tr>
<tr class="even">
<td>enes.vaseelah</td>
<td>PT8</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>male</td>
<td>69</td>
<td>02.01.2022</td>
<td>31.12.2022</td>
</tr>
<tr class="odd">
<td>ezwr1</td>
<td>PT9</td>
<td>Identified</td>
<td>TRUE</td>
<td>male</td>
<td>72</td>
<td>17.01.2022</td>
<td>28.12.2022</td>
</tr>
<tr class="even">
<td>fiete_boi</td>
<td>PT10</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>male</td>
<td>10</td>
<td>03.04.2022</td>
<td>04.11.2022</td>
</tr>
<tr class="odd">
<td>generation_islam</td>
<td>PT11</td>
<td>Identified</td>
<td>FALSE</td>
<td>male</td>
<td>18</td>
<td>29.04.2022</td>
<td>12.12.2022</td>
</tr>
<tr class="even">
<td>generation_islamgi</td>
<td>PT12</td>
<td>Identified</td>
<td>TRUE</td>
<td>male</td>
<td>71</td>
<td>25.01.2022</td>
<td>26.12.2022</td>
</tr>
<tr class="odd">
<td>gglaros</td>
<td>PT13</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>male</td>
<td>68</td>
<td>12.01.2022</td>
<td>25.12.2022</td>
</tr>
<tr class="even">
<td>gil.lua99</td>
<td>PT14</td>
<td>Not Identified</td>
<td>FALSE</td>
<td>male</td>
<td>65</td>
<td>01.01.2022</td>
<td>26.12.2022</td>
</tr>
<tr class="odd">
<td>hamzaadrianhamza</td>
<td>PT15</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>couple</td>
<td>72</td>
<td>07.05.2022</td>
<td>27.12.2022</td>
</tr>
<tr class="even">
<td>hidayaelisa</td>
<td>PT16</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>female</td>
<td>148</td>
<td>01.01.2022</td>
<td>31.12.2022</td>
</tr>
<tr class="odd">
<td>iman.vogue</td>
<td>PT17</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>female</td>
<td>105</td>
<td>10.06.2022</td>
<td>30.12.2022</td>
</tr>
<tr class="even">
<td>imauftragdesislam</td>
<td>PT18</td>
<td>Identified</td>
<td>TRUE</td>
<td>male</td>
<td>63</td>
<td>01.01.2022</td>
<td>13.07.2022</td>
</tr>
<tr class="odd">
<td>imjuliajordan</td>
<td>PT19</td>
<td>Not Identified</td>
<td>FALSE</td>
<td>female</td>
<td>10</td>
<td>22.01.2022</td>
<td>13.10.2022</td>
</tr>
<tr class="even">
<td>islam_moe</td>
<td>PT20</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>male</td>
<td>21</td>
<td>02.01.2022</td>
<td>28.12.2022</td>
</tr>
<tr class="odd">
<td>islamcontent5778ii</td>
<td>PT21</td>
<td>Identified</td>
<td>TRUE</td>
<td>male</td>
<td>72</td>
<td>27.08.2022</td>
<td>07.12.2022</td>
</tr>
<tr class="even">
<td>islamcontent778</td>
<td>PT22</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>male</td>
<td>80</td>
<td>05.07.2022</td>
<td>24.12.2022</td>
</tr>
<tr class="odd">
<td>islamic.wort</td>
<td>PT23</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>male</td>
<td>66</td>
<td>01.03.2022</td>
<td>27.12.2022</td>
</tr>
<tr class="even">
<td>islammzitate</td>
<td>PT24</td>
<td>Not Identified</td>
<td>FALSE</td>
<td>unknown</td>
<td>25</td>
<td>08.09.2022</td>
<td>18.12.2022</td>
</tr>
<tr class="odd">
<td>islamwunder</td>
<td>PT25</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>male</td>
<td>91</td>
<td>03.01.2022</td>
<td>19.11.2022</td>
</tr>
<tr class="even">
<td>isso_bayan</td>
<td>PT26</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>male</td>
<td>156</td>
<td>04.01.2022</td>
<td>31.12.2022</td>
</tr>
<tr class="odd">
<td>logical114</td>
<td>PT27</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>male</td>
<td>26</td>
<td>30.01.2022</td>
<td>27.12.2022</td>
</tr>
<tr class="even">
<td>loransyusuf</td>
<td>PT28</td>
<td>Identified</td>
<td>TRUE</td>
<td>male</td>
<td>81</td>
<td>22.01.2022</td>
<td>26.12.2022</td>
</tr>
<tr class="odd">
<td>loveallah.de</td>
<td>PT29</td>
<td>Identified</td>
<td>TRUE</td>
<td>male</td>
<td>156</td>
<td>01.01.2022</td>
<td>29.12.2022</td>
</tr>
<tr class="even">
<td>machtsklick_support</td>
<td>PT30</td>
<td>Identified</td>
<td>TRUE</td>
<td>male</td>
<td>93</td>
<td>10.01.2022</td>
<td>19.12.2022</td>
</tr>
<tr class="odd">
<td>mazooffiziell1</td>
<td>PT31</td>
<td>Not Identified</td>
<td>FALSE</td>
<td>male</td>
<td>18</td>
<td>02.01.2022</td>
<td>26.12.2022</td>
</tr>
<tr class="even">
<td>mert.islam.27</td>
<td>PT32</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>male</td>
<td>14</td>
<td>28.07.2022</td>
<td>13.08.2022</td>
</tr>
<tr class="odd">
<td>mira_eliane</td>
<td>PT33</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>female</td>
<td>50</td>
<td>06.01.2022</td>
<td>28.12.2022</td>
</tr>
<tr class="even">
<td>moe786hh</td>
<td>PT34</td>
<td>Identified</td>
<td>TRUE</td>
<td>male</td>
<td>155</td>
<td>10.01.2022</td>
<td>27.12.2022</td>
</tr>
<tr class="odd">
<td>mucahit_akif_uzun</td>
<td>PT35</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>male</td>
<td>47</td>
<td>06.01.2022</td>
<td>21.12.2022</td>
</tr>
<tr class="even">
<td>musliminteraktiv</td>
<td>PT36</td>
<td>Not Identified</td>
<td>FALSE</td>
<td>male</td>
<td>118</td>
<td>05.01.2022</td>
<td>30.12.2022</td>
</tr>
<tr class="odd">
<td>nalhi.23</td>
<td>PT37</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>male</td>
<td>64</td>
<td>01.01.2022</td>
<td>23.12.2022</td>
</tr>
<tr class="even">
<td>redlionx</td>
<td>PT38</td>
<td>Identified</td>
<td>TRUE</td>
<td>male</td>
<td>24</td>
<td>06.01.2022</td>
<td>22.11.2022</td>
</tr>
<tr class="odd">
<td>safi_muslimcouple</td>
<td>PT39</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>couple</td>
<td>59</td>
<td>01.01.2022</td>
<td>09.12.2022</td>
</tr>
<tr class="even">
<td>sakinaannur</td>
<td>PT40</td>
<td>Not Identified</td>
<td>TRUE</td>
<td>unknown</td>
<td>76</td>
<td>01.01.2022</td>
<td>26.12.2022</td>
</tr>
<tr class="odd">
<td>sarikliyunus</td>
<td>PT41</td>
<td>Not Identified</td>
<td>FALSE</td>
<td>male</td>
<td>50</td>
<td>04.01.2022</td>
<td>30.12.2022</td>
</tr>
<tr class="even">
<td>teamsad.1</td>
<td>PT42</td>
<td>Not Identified</td>
<td>FALSE</td>
<td>male</td>
<td>156</td>
<td>02.01.2022</td>
<td>30.12.2022</td>
</tr>
<tr class="odd">
<td>youngmuslimofficial</td>
<td>PT43</td>
<td>Identified</td>
<td>TRUE</td>
<td>male</td>
<td>54</td>
<td>11.01.2022</td>
<td>30.12.2022</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/act_overall-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-6-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-3-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/act_account-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>